name: nvs_trading
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_otp_text_field: ^1.1.1 ## mã số OTP
  dotted_decoration: ^2.0.0 ## Vẽ nét đứt
  image_picker: ^1.0.7  ## Tải/ chụp ảnh
  google_fonts: ^6.2.1 ## gg fonts
  dio: ^5.4.1 ## call api
  dropdown_button2: ^2.3.9 ## dropdown button 2
  dropdownfield2: ^1.0.7 ## dropdown textfield
  multi_dropdown: ^2.1.4 ## dropdown chọn nhiều 
  searchfield: ^1.0.1
  intl: any
  flutter_localization: ^0.2.0
  flutter_svg: ^2.0.10+1 ## hiển thị file svg
  syncfusion_flutter_pdfviewer: ^24.2.8 ## hiển thị file pdf
  socket_io_client: ^2.0.3+1 ##socket io
  web_socket_channel: ^2.4.5 ##socket realtime
  lzstring: ^2.0.0+2 ##lzstring

  fluttertoast: ^8.2.4 ## show messages
  toast: ^0.3.0 
  awesome_notifications: ^0.8.2 ## notification cho phone
  webview_flutter: ^4.7.0 ## trading view
  ## Bloc and storage
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  hydrated_bloc: ^9.1.4
  path_provider: ^2.1.2
  json_annotation: ^4.9.0

  provider: ^6.1.2
  ##
  shared_preferences: ^2.2.2
  freezed_annotation: ^2.4.1

  local_auth: ^2.2.0 ## sinh trac hoc
  http: ^1.2.1

  ## doc html
  html: ^0.15.4
  ## chart
  d_chart: ^2.6.9
  
  bloc: ^8.1.4
  meta: ^1.11.0
  copy_with_extension: ^5.0.4
  get_it: ^7.7.0
    ## auto size text
  auto_size_text: ^3.0.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/bank/
    - assets/env/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

